version: "3.9"
services:
  app:
    container_name: phpcli
    build:
      context: .
      dockerfile: ./docker/phpcli/Dockerfile
    tty: true
    stdin_open: true
    command:
      - bash
      - "-c"
      - |
        composer install
        php artisan key:generate
        php -a
    volumes:
      - .:/var/www/PokeRank
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
  db:
    container_name: mysql
    image: mysql:8.0.19
    command: |
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
  # node:
  #   container_name: node
  #   image: node:16.10.0
  #   command:
  #     - bash
  #     - "-c"
  #     - |
  #       cd /PokeRank/resources/poke-rank && npm install && npm run start
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/PokeRank
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
      