version: "3.9"
services:
  app:
    container_name: phpfpm
    build:
      context: .
      dockerfile: ./docker/prod/phpfpm/Dockerfile
    depends_on:
      - db
    command:
      - bash
      - "-c"
      - |
        mv /PokeRank/* /var/www/PokeRank
        mv /PokeRank/.* /var/www/PokeRank
        cp /var/www/PokeRank/.env.example /var/www/PokeRank/.env

        chown -R www-data:www-data /var/www/PokeRank
        chmod -R 755 /var/www/PokeRank

        php artisan key:generate
        php artisan storage:link
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

        php-fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - webapp:/var/www/PokeRank
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
  webserver:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
    volumes:
      - webapp:/var/www/PokeRank
    environment:
      PHPFPM_HOSTNAME: phpfpm
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
  db:
    container_name: mysql
    image: mysql:8.0.19
    command: |
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  webapp:
    driver: local
      